---
- name: Niezależny playbook aktualizacji Bugfix
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Aktualizacja RHEL 8 (Bugfix)
      command: dnf update --bugfix -y
      when: ansible_distribution_major_version == '8'

    - name: Aktualizacja RHEL 9 (Bugfix)
      dnf:
        name: '*'
        state: latest
        bugfix: yes
      when: ansible_distribution_major_version == '9'
