---
- name: Sprawdź i raportuj aktualizacje RHEL z podziałem na typy
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    # Sekcja dla RHEL 8
    - name: Sprawdź aktualizacje dla RHEL 8
      block:
        - name: Pobierz listę (Security i Bugfix)
          command: "dnf check-update --{{ item }}"
          register: dnf_check
          loop:
            - security
            - bugfix
          failed_when: dnf_check.rc not in [0, 100]
          changed_when: false
          
        - name: Wyświetl wyniki dla RHEL 8
          debug:
            msg: "Host: {{ inventory_hostname }} | Dostępne aktualizacje {{ item.item }}: {{ item.stdout_lines }}"
          loop: "{{ dnf_check.results }}"
          when: item.rc == 100
      when: ansible_distribution_major_version == '8'

    # Sekcja dla RHEL 9+
    - name: Sprawdź aktualizacje dla RHEL 9+
      block:
        - name: Pobierz listę (Security i Bugfix)
          dnf:
            list: updates
            security: "{{ item == 'security' }}"
            bugfix: "{{ item == 'bugfix' }}"
          register: dnf_list
          loop:
            - security
            - bugfix
          
        - name: Wyświetl wyniki dla RHEL 9+
          debug:
            msg: "Host: {{ inventory_hostname }} | Dostępne aktualizacje {{ item.item }}: {{ item.results | map(attribute='name') | list }}"
          loop: "{{ dnf_list.results }}"
          when: item.results | length > 0
      when: ansible_distribution_major_version | int >= 9
