---
- name: Security updates
  hosts: all
  gather_facts: false 
  tasks:
    # Używamy raw do wszystkiego, co może dotknąć ósemki.
    # Raw nie używa bibliotek Ansible na maszynie docelowej.
    - name: Update RHEL 8
      raw: dnf update --security -y
      when: "'8' in ansible_distribution_major_version | default('9')"

    - name: Update RHEL 9
      dnf:
        name: '*'
        state: latest
        security: yes
      when: "'9' in ansible_distribution_major_version | default('9')"

