# Plik: tasks/security_updates.yml
# BEZ LINI "hosts:", "name:" (dla play), i "gather_facts:"

- name: Aktualizacja RHEL 8
  command: dnf update --security -y
  when: ansible_distribution_major_version == '8'

- name: Aktualizacja RHEL 9
  dnf:
    name: '*'
    state: latest
    security: yes
  when: ansible_distribution_major_version == '9'

